version: '2'
services:
  statsd:
    image: hopsoft/graphite-statsd
    restart: always
    ports:
     - "81:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
  grafana:
    image: grafana/grafana
    depends_on:
     - statsd
    links:
     - statsd
    ports:
     - "80:3000"
